# frozen_string_literal: true

# Homebrew formula for `eypres` (Apple silicon macOS only).
#
# The tap is hosted in the source repository itself — `brew tap
# really-knows-ai/ey-present <git url>` — so the tap root *is* this repo and
# `Formula/` is the tap's formula directory.
#
# `eypres` is distributed from the private repository really-knows-ai/ey-present
# and only a darwin/arm64 binary is built. The public release-download URL
# below cannot be fetched anonymously, so it is resolved through the GitHub API
# by the custom strategy in lib/, using the user's HOMEBREW_GITHUB_API_TOKEN.
#
# ---------------------------------------------------------------------------
# REGENERATION CONTRACT (phase-9 task-5 release.yml manifest job)
# ---------------------------------------------------------------------------
# On every release the manifest job rewrites exactly three lines of this file
# from the freshly published release, and nothing else:
#
#   1. version "X.Y.Z"                 <- the pushed tag, without the leading "v"
#   2. url  .../download/vX.Y.Z/eypres-darwin-arm64
#                                      <- release URL pattern
#                                         https://github.com/really-knows-ai/ey-present/releases/download/vX.Y.Z/eypres-darwin-arm64
#   3. sha256 "..."                    <- the SHA-256 of eypres-darwin-arm64 as
#                                         printed in the release's checksums.txt
#
# The asset name is fixed: `eypres-darwin-arm64` (see the Makefile `release`
# target). `depends_on :macos` / the strategy are not touched by regeneration.

require_relative "lib/github_private_release_download_strategy"

# Formula for the eypres single binary, fetched from the private release.
class Eypres < Formula
  desc "EY Markdown presentation tool (Apple silicon)"
  homepage "https://github.com/really-knows-ai/ey-present"
  # PLACEHOLDER: version/url/sha256 are regenerated by the release manifest job
  # (phase-9 task-5) — see the regeneration contract above. The URL must stay in
  # the release-download form so the custom strategy can parse it.
  url "https://github.com/really-knows-ai/ey-present/releases/download/v0.0.0/eypres-darwin-arm64",
      using: GitHubPrivateReleaseDownloadStrategy
  version "0.0.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license :cannot_represent

  # Only a darwin/arm64 binary is built. Refuse Intel Macs before anything is
  # downloaded, with a plain-language explanation. This cannot live in an
  # `on_intel` block: Homebrew only allows dependency-style declarations there,
  # not a hard stop.
  if Hardware::CPU.intel?
    odie <<~EOS
      eypres is Apple silicon only.

      No Intel (darwin/amd64) build is provided. Please install eypres on a Mac
      with an Apple silicon (M-series) chip.
    EOS
  end

  def install
    bin.install "eypres-darwin-arm64" => "eypres"
  end

  def caveats
    <<~EOS
      eypres is a single self-contained binary. Run `eypres init` in an empty
      folder to create a starter deck, then `eypres start`.
    EOS
  end

  test do
    output = shell_output("#{bin}/eypres templates")
    assert_match(/Built-in templates/, output)
    assert_match(/\btitle\b/, output)
  end
end
