# frozen_string_literal: true

# Homebrew formula for `kalide` (macOS, Apple silicon and Intel).
#
# The tap is hosted in the source repository itself, so the tap root *is* this
# repo and `Formula/` is the tap's formula directory:
#
#   brew tap really-knows-ai/kalide https://github.com/really-knows-ai/kalide
#   brew install kalide
#
# Both darwin/arm64 and darwin/amd64 binaries are downloaded anonymously from
# the public GitHub Release; no token or credentials are needed.
#
# ---------------------------------------------------------------------------
# REGENERATION CONTRACT (release.yml manifest job)
# ---------------------------------------------------------------------------
# On every release the manifest job rewrites exactly version and TWO
# url/sha256 pairs (one per architecture) from the freshly published release,
# and nothing else:
#
#   1. version "X.Y.Z"                 <- the pushed tag, without the leading "v"
#   2. the `else` branch's url  .../download/vX.Y.Z/kalide-darwin-arm64
#      the `else` branch's sha256 "..." <- SHA-256 of kalide-darwin-arm64 as
#                                           printed in the release's checksums.txt
#   3. the `if Hardware::CPU.intel?` branch's url  .../download/vX.Y.Z/kalide-darwin-amd64
#      the `if Hardware::CPU.intel?` branch's sha256 "..." <- SHA-256 of
#                                           kalide-darwin-amd64 as printed in
#                                           the release's checksums.txt
#
# The asset names are fixed: `kalide-darwin-arm64` and `kalide-darwin-amd64`
# (see the Makefile `release` target). Each `url` line must be immediately
# followed by its `sha256` line.

# Formula for the kalide single binary, fetched from the public release.
class Kalide < Formula
  desc "Markdown presentation tool"
  homepage "https://github.com/really-knows-ai/kalide"
  version "0.10.0"
  license "Apache-2.0"

  # url/sha256 pairs below are regenerated by the release manifest job — see
  # the regeneration contract above.
  if Hardware::CPU.intel?
    url "https://github.com/really-knows-ai/kalide/releases/download/v0.10.0/kalide-darwin-amd64"
    sha256 "c6c1daa59c40b11fb519bb76232d337ba25522feef91bce7de875fb157dd67e4"
  else
    url "https://github.com/really-knows-ai/kalide/releases/download/v0.10.0/kalide-darwin-arm64"
    sha256 "26cd6406a85cbb3888763e37f17dbf13a94394738fe4ae5541a3c4b8181a7fa5"
  end

  def install
    asset_name = Hardware::CPU.arm? ? "kalide-darwin-arm64" : "kalide-darwin-amd64"
    bin.install asset_name => "kalide"
  end

  def caveats
    <<~EOS
      kalide is a single self-contained binary. Run `kalide init` in an empty
      folder to create a starter deck, then `kalide start`.
    EOS
  end

  test do
    system bin/"kalide", "init"
    output = shell_output("#{bin}/kalide templates")
    assert_match(/\bhello\b/, output)
  end
end
